# Make the application available at http://localhost:7070/authserver

server:
  port: 7070
  contextPath: /authserver

# Our certificate settings for enabling JWT tokens

jwt:
  certificate:
    store:
      file: classpath:/certificate/mytest.jks
      password: mypass
    key:
      alias: mytest
      password: mypass

      
security:
  oauth2:
    resource: 
      filter-order: 3
      