info:
  component: Edge Server
  
zuul:
  prefix: /api
  routes:
   simple:
    path: /simple/**
    serviceId: simple-service
   other:
    path: /other/**
    serviceId: other-service
    
eureka:
  client:
    service-url:
     defaultZone: http://localhost:8761/eureka/
    register-with-eureka: false
    
server:
  port: 8765
 
  