server:
  port: 8092

spring:
  application:
    name: Other-Service
    
eureka:
  client:
    register-with-eureka: false
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka