server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  server:
      enable-self-preservation: false
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/