server:
  port: 8761
  
security:
  basic:
     enabled: true
  user:
     name: admin
     password: admin

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://admin:admin@localhost:8761/eureka/

